/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminScholarshipsRouteImport } from './routes/_authenticated/admin.scholarships'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/admin/applications',
    path: '/admin/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminScholarshipsRoute =
  AuthenticatedAdminScholarshipsRouteImport.update({
    id: '/admin/scholarships',
    path: '/admin/scholarships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/concierge': typeof ConciergeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/universities': typeof UniversitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/articles/': typeof ArticlesIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/scholarships': typeof AuthenticatedAdminScholarshipsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/concierge': typeof ConciergeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/universities': typeof UniversitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/articles': typeof ArticlesIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/scholarships': typeof AuthenticatedAdminScholarshipsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/concierge': typeof ConciergeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/universities': typeof UniversitiesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/articles/': typeof ArticlesIndexRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/scholarships': typeof AuthenticatedAdminScholarshipsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/concierge'
    | '/how-it-works'
    | '/universities'
    | '/dashboard'
    | '/articles/'
    | '/admin/applications'
    | '/admin/scholarships'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/concierge'
    | '/how-it-works'
    | '/universities'
    | '/dashboard'
    | '/articles'
    | '/admin/applications'
    | '/admin/scholarships'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/concierge'
    | '/how-it-works'
    | '/universities'
    | '/_authenticated/dashboard'
    | '/articles/'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/scholarships'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConciergeRoute: typeof ConciergeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  UniversitiesRoute: typeof UniversitiesRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/scholarships': {
      id: '/_authenticated/admin/scholarships'
      path: '/admin/scholarships'
      fullPath: '/admin/scholarships'
      preLoaderRoute: typeof AuthenticatedAdminScholarshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminScholarshipsRoute: typeof AuthenticatedAdminScholarshipsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminScholarshipsRoute: AuthenticatedAdminScholarshipsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConciergeRoute: ConciergeRoute,
  HowItWorksRoute: HowItWorksRoute,
  UniversitiesRoute: UniversitiesRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
